services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - minio-network
    restart: on-failure

  db-project-1:
    image: postgres:13
    environment:
      POSTGRES_USER: project1_user
      POSTGRES_PASSWORD: project1_password
      POSTGRES_DB: project1_db
    volumes:
      - project1_data:/var/lib/postgresql/data
      - ./initial_db/project-1:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "5431:5432"

  db-process:
    image: postgres:13
    environment:
      POSTGRES_USER: process_user
      POSTGRES_PASSWORD: process_password
      POSTGRES_DB: process_db
    volumes:
      - process_data:/var/lib/postgresql/data
      - ./initial_db/process:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "5432:5432"

  project-1:
    image: project-1
    build:
      context: ./project-1
      dockerfile: Dockerfile
    depends_on:
      - db-project-1
      - minio
    environment:
      DB_HOST: db-project-1
      DB_USER: project1_user
      DB_PASSWORD: project1_password
      DB_NAME: project1_db
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET_NAME: project-1-bucket
    networks:
      - backend
      - minio-network
    volumes:
      - ./project-1/app/transactions:/usr/src/app/transactions
    command: python /usr/src/app/app/main.py
    restart: on-failure

  etl-process:
    image: etl-process
    build:
      context: ./process
      dockerfile: Dockerfile
    depends_on:
      - project-1
      - db-process
    environment:
      DB_HOST: db-process
      DB_USER: process_user
      DB_PASSWORD: process_password
      DB_NAME: process_db
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET_NAME: project-1-bucket
    volumes:
      - ./process/app/downloads:/usr/src/app/downloads
    networks:
      - backend
      - minio-network
    command: python /usr/src/app/app/main.py
    restart: on-failure

networks:
  backend:
  minio-network:

volumes:
  project1_data:
  process_data:
  minio_data:
