services:
  db-project-1:
    image: postgres:13
    environment:
      POSTGRES_USER: project1_user
      POSTGRES_PASSWORD: project1_password
      POSTGRES_DB: project1_db
    volumes:
      - project1_data:/var/lib/postgresql/data
      - ./initial_db/project-1:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "5431:5432"

  db-process:
    image: postgres:13
    environment:
      POSTGRES_USER: process_user
      POSTGRES_PASSWORD: process_password
      POSTGRES_DB: process_db
    volumes:
      - process_data:/var/lib/postgresql/data
      - ./initial_db/process:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "5432:5432"

  project-1:
    image: project-1
    build:
      context: ./project-1
      dockerfile: Dockerfile
    depends_on:
      - db-project-1
    environment:
      DB_HOST: db-project-1
      DB_USER: project1_user
      DB_PASSWORD: project1_password
      DB_NAME: project1_db
    networks:
      - backend
    volumes:
      - ./project-1/app/transactions:/usr/src/app/transactions
    command: python /usr/src/app/app/main.py
    restart: on-failure

  process-service:
    build:
      context: ./process
      dockerfile: Dockerfile
    depends_on:
      - project-1
      - db-process
    environment:
      CSV_PATH: /usr/src/app/transactions/transactions.csv
      DB_PROJECT1_HOST: db-project-1
      DB_PROJECT1_USER: project1_user
      DB_PROJECT1_PASSWORD: project1_password
      DB_PROJECT1_NAME: project1_db
      DB_PROCESS_HOST: db-process
      DB_PROCESS_USER: process_user
      DB_PROCESS_PASSWORD: process_password
      DB_PROCESS_NAME: process_db
    volumes:
      - ./project-1/app/transactions:/usr/src/app/transactions
    networks:
      - backend
    command: python /usr/src/app/main.py
    restart: on-failure

networks:
  backend:

volumes:
  project1_data:
  process_data:
