INSERT INTO master.m_account_types (code, name, group_name, row_status)
VALUES 
    ('IND', 'Individual Account', 'INDIVIDUAL', 'active'),
    ('BUS', 'Business Account', 'BUSINESS', 'active'),
    ('ENT', 'Enterprise Account', 'ENTERPRISE', 'active'),
    ('FREE', 'Free Tier Account', 'FREE_TIER', 'active');

INSERT INTO master.m_accounts (code, name, account_type_id, parent_account_id, created_by, created_date, updated_by, updated_date, row_status)
VALUES 
    ('747443860322', '่john-doe', (SELECT id FROM master.m_account_types WHERE code = 'IND'), NULL, 'System', current_timestamp, NULL, NULL, 'active'),
    ('774890550382', 'jane-smith', (SELECT id FROM master.m_account_types WHERE code = 'IND'), NULL, 'System', current_timestamp, NULL, NULL, 'active');

INSERT INTO master.m_accounts (code, name, account_type_id, parent_account_id, created_by, created_date, row_status)
VALUES 
    ('441682894486', 'Ascend Group', (SELECT id FROM master.m_account_types WHERE code = 'ENT'), NULL, 'System', current_timestamp, 'active'),
    ('772313499959', 'True Corporation', (SELECT id FROM master.m_account_types WHERE code = 'ENT'), NULL, 'System', current_timestamp, 'active');

INSERT INTO master.m_accounts (code, name, account_type_id, parent_account_id, created_by, created_date, row_status)
VALUES 
    ('429092326773', 'ascend-money', (SELECT id FROM master.m_account_types WHERE code = 'ENT'), (SELECT id FROM master.m_accounts WHERE name = 'Ascend Group'), 'System', current_timestamp, 'active'),
    ('936922002519', 'ascend-commerce', (SELECT id FROM master.m_account_types WHERE code = 'ENT'), (SELECT id FROM master.m_accounts WHERE name = 'Ascend Group'), 'System', current_timestamp, 'active'),
    ('116819170887', 'true-idc', (SELECT id FROM master.m_account_types WHERE code = 'ENT'), (SELECT id FROM master.m_accounts WHERE name = 'Ascend Group'), 'System', current_timestamp, 'active'),
    ('655484151593', 'ascend-bit', (SELECT id FROM master.m_account_types WHERE code = 'BUS'), (SELECT id FROM master.m_accounts WHERE name = 'Ascend Group'), 'System', current_timestamp, 'active'),
    ('912577240677', 'egg-digital', (SELECT id FROM master.m_account_types WHERE code = 'BUS'), (SELECT id FROM master.m_accounts WHERE name = 'Ascend Group'), 'System', current_timestamp, 'active');

INSERT INTO master.m_accounts (code, name, account_type_id, parent_account_id, created_by, created_date, row_status)
VALUES 
    ('998795981022', 'truemove-h', (SELECT id FROM master.m_account_types WHERE code = 'ENT'), (SELECT id FROM master.m_accounts WHERE name = 'True Corporation'), 'System', current_timestamp, 'active'),
    ('684957738202', 'true-visions', (SELECT id FROM master.m_account_types WHERE code = 'ENT'), (SELECT id FROM master.m_accounts WHERE name = 'True Corporation'), 'System', current_timestamp, 'active'),
    ('682545126939', 'true-online', (SELECT id FROM master.m_account_types WHERE code = 'ENT'), (SELECT id FROM master.m_accounts WHERE name = 'True Corporation'), 'System', current_timestamp, 'active');

INSERT INTO master.m_discount_programs (code, name, discount_type, unit_type, min_value, max_value, start_date, end_date, created_by, created_date, row_status)
VALUES 
    ('SPP', 'Solution Provider Program', 'fixed', 'percentage', 3, 8, '2024-01-01', NULL, 'System', current_timestamp, 'active'),
    ('EDP', 'Enterprise Discount Program', 'fixed', 'percentage', 10.00, 30.00, '2024-01-01', NULL, 'System', current_timestamp, 'active');

INSERT INTO master.m_account_discount_programs (account_id, discount_program_id, min_value, is_forwarded, created_by, created_date, row_status)
VALUES 
    -- For Inidividual
    ((SELECT id FROM master.m_accounts WHERE code = '747443860322'), (SELECT id FROM master.m_discount_programs WHERE code = 'SPP'), 5.00, FALSE, 'System', current_timestamp, 'active'),
    ((SELECT id FROM master.m_accounts WHERE code = '774890550382'), (SELECT id FROM master.m_discount_programs WHERE code = 'SPP'), 8.00, FALSE, 'System', current_timestamp, 'active'),

    -- For Ascend Group
    ((SELECT id FROM master.m_accounts WHERE code = '441682894486'), (SELECT id FROM master.m_discount_programs WHERE code = 'EDP'), 15.00, FALSE, 'System', current_timestamp, 'active'),
    ((SELECT id FROM master.m_accounts WHERE code = '429092326773'), (SELECT id FROM master.m_discount_programs WHERE code = 'EDP'), 10.00, FALSE, 'System', current_timestamp, 'active'),
    ((SELECT id FROM master.m_accounts WHERE code = '936922002519'), (SELECT id FROM master.m_discount_programs WHERE code = 'EDP'), 10.00, FALSE, 'System', current_timestamp, 'active'),
    ((SELECT id FROM master.m_accounts WHERE code = '116819170887'), (SELECT id FROM master.m_discount_programs WHERE code = 'EDP'), 10.00, FALSE, 'System', current_timestamp, 'active'),
    ((SELECT id FROM master.m_accounts WHERE code = '655484151593'), (SELECT id FROM master.m_discount_programs WHERE code = 'EDP'), 10.00, FALSE, 'System', current_timestamp, 'active'),
    ((SELECT id FROM master.m_accounts WHERE code = '912577240677'), (SELECT id FROM master.m_discount_programs WHERE code = 'EDP'), 10.00, FALSE, 'System', current_timestamp, 'active'),

    -- For TRUE
    ((SELECT id FROM master.m_accounts WHERE code = '772313499959'), (SELECT id FROM master.m_discount_programs WHERE code = 'EDP'), 18.00, TRUE, 'System', current_timestamp, 'active');
    -- ((SELECT id FROM master.m_accounts WHERE code = '998795981022'), (SELECT id FROM master.m_discount_programs WHERE code = 'EDP'), 18.00, FALSE, 'System', current_timestamp, 'active'),
    -- ((SELECT id FROM master.m_accounts WHERE code = '684957738202'),(SELECT id FROM master.m_discount_programs WHERE code = 'EDP'), 18.00, FALSE, 'System', current_timestamp, 'active'),
    -- ((SELECT id FROM master.m_accounts WHERE code = '682545126939'), (SELECT id FROM master.m_discount_programs WHERE code = 'EDP'), 18.00, FALSE, 'System', current_timestamp, 'active');

INSERT INTO project.t_projects (code, name, account_id, description, created_by, created_date, row_status)
VALUES 
    -- For Individual Accounts
    ('A1B2C3D4E5F6', 'john_doe_initiative', (SELECT id FROM master.m_accounts WHERE code = '747443860322'), 'A personalized project for John Doe focused on enhancing user experience.', 'System', current_timestamp, 'active'),
    ('G7H8I9J0K1L2', 'jane_smith_venture', (SELECT id FROM master.m_accounts WHERE code = '774890550382'), 'An innovative project led by Jane Smith to streamline service delivery.', 'System', current_timestamp, 'active'),

    -- For Ascend Group
    ('M3N4O5P6Q7R8', 'ascend_group_strategy', (SELECT id FROM master.m_accounts WHERE code = '441682894486'), 'A strategic initiative to expand Ascend Group’s market reach.', 'System', current_timestamp, 'active'),
    ('S9T0U1V2W3X4', 'ascend_money_platform', (SELECT id FROM master.m_accounts WHERE code = '429092326773'), 'Development of a digital platform for Ascend Money to enhance financial services.', 'System', current_timestamp, 'active'),
    ('Y5Z6A7B8C9D0', 'ascend_commerce_experience', (SELECT id FROM master.m_accounts WHERE code = '936922002519'), 'A project aimed at transforming the e-commerce experience for Ascend Commerce.', 'System', current_timestamp, 'active'),
    ('E1F2G3H4I5J6', 'ascend_idc_innovation', (SELECT id FROM master.m_accounts WHERE code = '116819170887'), 'Innovation initiative for Ascend IDC focusing on cloud solutions.', 'System', current_timestamp, 'active'),
    ('K2L3M4N5O6P7', 'ascend_bit_transformation', (SELECT id FROM master.m_accounts WHERE code = '655484151593'), 'Digital transformation project for Ascend Bit to improve operational efficiency.', 'System', current_timestamp, 'active'),
    ('Q8R9S0T1U2V3', 'egg_digital_revolution', (SELECT id FROM master.m_accounts WHERE code = '912577240677'), 'A revolutionary project to redefine digital marketing strategies for Egg Digital.', 'System', current_timestamp, 'active'),

    -- For True Corporation
    ('W4X5Y6Z7A8B9', 'true_corporation_growth', (SELECT id FROM master.m_accounts WHERE code = '772313499959'), 'Growth initiative for True Corporation focusing on expanding service offerings.', 'System', current_timestamp, 'active'),
    ('C0D1E2F3G4H5', 'truemove_h_engagement', (SELECT id FROM master.m_accounts WHERE code = '998795981022'), 'A project aimed at enhancing customer engagement for Truemove H.', 'System', current_timestamp, 'active'),
    ('I6J7K8L9M0N1', 'true_visions_initiative', (SELECT id FROM master.m_accounts WHERE code = '684957738202'), 'Initiative to explore innovative solutions for True Visions.', 'System', current_timestamp, 'active'),
    ('O2P3Q4R5S6T7', 'true_online_service', (SELECT id FROM master.m_accounts WHERE code = '682545126939'), 'A project to enhance online services and user experience for True Online.', 'System', current_timestamp, 'active');

-- Insert mock data into product.m_product_categories with AWS service categories
INSERT INTO product.m_product_categories (code, name, description, row_status, created_by)
VALUES 
    ('COMPUTE', 'Compute', 'Services for scalable compute capacity in the cloud, such as EC2, Lambda', 'active', 'System'),
    ('STORAGE', 'Storage', 'Services for scalable and secure storage solutions like S3, EBS, Glacier', 'active', 'System'),
    ('DATABASE', 'Database', 'Managed database services like RDS, DynamoDB, Redshift', 'active', 'System'),
    ('NETWORKING', 'Networking', 'Services for connecting and securing networks, such as VPC, CloudFront', 'active', 'System'),
    ('SECURITY', 'Security', 'Tools for data protection and security compliance, like IAM, KMS', 'active', 'System'),
    ('ANALYTICS', 'Analytics', 'Data analytics services like EMR, Athena, QuickSight', 'active', 'System'),
    ('ML_AI', 'Machine Learning & AI', 'Machine learning and AI services, like SageMaker, Rekognition', 'active', 'System'),
    ('DEVTOOLS', 'Developer Tools', 'Services for development and CI/CD, such as CodeCommit, CodeBuild', 'active', 'System'),
    ('IOT', 'Internet of Things', 'Services for IoT device management and analytics, such as IoT Core', 'active', 'System'),
    ('MIGRATION', 'Migration', 'Tools for migrating applications to AWS, like DMS, Snowball', 'active', 'System');

-- Insert mock data into product.m_products, one product per category
INSERT INTO product.m_products (code, name, description, product_category_id, row_status, created_by)
VALUES 
    ('EC2', 'Amazon EC2', 'Scalable virtual server instance on AWS.', (SELECT id FROM product.m_product_categories WHERE code = 'COMPUTE'), 'active', 'System'),
    ('S3', 'Amazon S3', 'Object storage service for data storage and retrieval.', (SELECT id FROM product.m_product_categories WHERE code = 'STORAGE'), 'active', 'System'),
    ('RDS', 'Amazon RDS', 'Managed relational database service for MySQL, PostgreSQL, and more.', (SELECT id FROM product.m_product_categories WHERE code = 'DATABASE'), 'active', 'System'),
    ('VPC', 'Amazon VPC', 'Virtual private cloud to securely isolate AWS resources.', (SELECT id FROM product.m_product_categories WHERE code = 'NETWORKING'), 'active', 'System'),
    ('IAM', 'AWS IAM', 'Identity and access management for AWS accounts.', (SELECT id FROM product.m_product_categories WHERE code = 'SECURITY'), 'active', 'System'),
    ('ATHENA', 'Amazon Athena', 'Interactive query service to analyze data in Amazon S3.', (SELECT id FROM product.m_product_categories WHERE code = 'ANALYTICS'), 'active', 'System'),
    ('SAGEMAKER', 'Amazon SageMaker', 'Fully managed service for building and deploying ML models.', (SELECT id FROM product.m_product_categories WHERE code = 'ML_AI'), 'active', 'System'),
    ('CODEBUILD', 'AWS CodeBuild', 'Fully managed continuous integration service.', (SELECT id FROM product.m_product_categories WHERE code = 'DEVTOOLS'), 'active', 'System'),
    ('IOT_CORE', 'AWS IoT Core', 'Service for connecting IoT devices to the cloud.', (SELECT id FROM product.m_product_categories WHERE code = 'IOT'), 'active', 'System'),
    ('DMS', 'AWS DMS', 'Database Migration Service for migrating databases to AWS.', (SELECT id FROM product.m_product_categories WHERE code = 'MIGRATION'), 'active', 'System');

INSERT INTO product.m_product_specifications (code, name, description, product_id, specification, unit, row_status, created_by) VALUES 
    ('EC2-T3', 'Amazon EC2 T3', 'Burstable, cost-effective instances with a balance of compute, memory, and network resources.', (SELECT id FROM product.m_products WHERE code = 'EC2'), '{"cpu": "2 vCPU", "memory": "4 GiB"}', 'instance', 'active', 'System'),
    ('S3-STANDARD', 'Amazon S3 Standard', 'General-purpose storage class for frequently accessed data.', (SELECT id FROM product.m_products WHERE code = 'S3'), '{"storage_class": "Standard", "durability": "99.999999999%", "availability": "99.99%"}', 'GB', 'active', 'System'),
    ('RDS-POSTGRES', 'Amazon RDS PostgreSQL', 'Managed relational database service with PostgreSQL.', (SELECT id FROM product.m_products WHERE code = 'RDS'), '{"engine": "PostgreSQL", "version": "13"}', 'database', 'active', 'System'),
    ('VPC', 'Amazon VPC', 'Virtual Private Cloud for provisioning isolated network resources.', (SELECT id FROM product.m_products WHERE code = 'VPC'), '{"cidr_block": "10.0.0.0/16", "subnets": 3}', 'vpc', 'active', 'System'),
    ('IAM-USER', 'AWS IAM User', 'User identity within AWS account to access resources.', (SELECT id FROM product.m_products WHERE code = 'IAM'), '{"max_policies": 10, "access_keys": "2"}', 'user', 'active', 'System'),
    ('ATHENA-STD', 'Amazon Athena', 'Interactive query service to analyze data in Amazon S3.', (SELECT id FROM product.m_products WHERE code = 'ATHENA'), '{"query_limit": "100 MB", "timeout": "5 minutes"}', 'query', 'active', 'System'),
    ('SAGEMAKER-ENDPOINT', 'Amazon SageMaker Endpoint', 'Service for deploying machine learning models at scale.', (SELECT id FROM product.m_products WHERE code = 'SAGEMAKER'), '{"training_data": "100 GB", "runtime": "Python 3"}', 'endpoint', 'active', 'System'),
    ('CODEBUILD-BASIC', 'AWS CodeBuild', 'Fully managed continuous integration service.', (SELECT id FROM product.m_products WHERE code = 'CODEBUILD'), '{"cpu": "4 vCPU", "memory": "7 GB"}', 'build', 'active', 'System'),
    ('IOT_CORE', 'AWS IoT Core', 'Platform to connect IoT devices to the cloud.', (SELECT id FROM product.m_products WHERE code = 'IOT_CORE'), '{"max_messages": "100,000", "qos": "1"}', 'device', 'active', 'System'),
    ('DMS-BASIC', 'AWS DMS', 'Database Migration Service to migrate data to AWS securely and quickly.', (SELECT id FROM product.m_products WHERE code = 'DMS'), '{"migration_speed": "1 TB/day", "support": "full load and CDC"}', 'migration', 'active', 'System');

INSERT INTO product.m_pricing_model (product_id, product_spec_id, billing_cycle, pricing_unit, price_per_unit, tier, usage_value, usage_type, row_status, created_by) VALUES 
    ((SELECT id FROM product.m_products WHERE code = 'EC2'), (SELECT id FROM product.m_product_specifications WHERE code = 'EC2-T3'), 'monthly', 'instance hour', 0.020, NULL, 100.0, 'on-demand', 'active', 'System'),
    ((SELECT id FROM product.m_products WHERE code = 'S3'), (SELECT id FROM product.m_product_specifications WHERE code = 'S3-STANDARD'), 'monthly', 'GB', 0.023, NULL, 5000.0, 'storage', 'active', 'System'),
    ((SELECT id FROM product.m_products WHERE code = 'RDS'), (SELECT id FROM product.m_product_specifications WHERE code = 'RDS-POSTGRES'), 'hourly', 'database hour', 0.250, NULL, 200.0, 'on-demand', 'active', 'System'),
    ((SELECT id FROM product.m_products WHERE code = 'VPC'), (SELECT id FROM product.m_product_specifications WHERE code = 'VPC'), 'monthly', 'vpc', 0.000, NULL, 1.0, 'free-tier', 'active', 'System'),
    ((SELECT id FROM product.m_products WHERE code = 'IAM'), (SELECT id FROM product.m_product_specifications WHERE code = 'IAM-USER'), 'monthly', 'user', 0.000, NULL, 10.0, 'free-tier', 'active', 'System'),
    ((SELECT id FROM product.m_products WHERE code = 'ATHENA'), (SELECT id FROM product.m_product_specifications WHERE code = 'ATHENA-STD'), 'query', 'per TB scanned', 5.000, NULL, NULL, 'usage', 'active', 'System'),
    ((SELECT id FROM product.m_products WHERE code = 'SAGEMAKER'), (SELECT id FROM product.m_product_specifications WHERE code = 'SAGEMAKER-ENDPOINT'), 'monthly', 'endpoint hour', 0.100, NULL, 100.0, 'inference', 'active', 'System'),
    ((SELECT id FROM product.m_products WHERE code = 'CODEBUILD'), (SELECT id FROM product.m_product_specifications WHERE code = 'CODEBUILD-BASIC'), 'build', 'minute', 0.003, NULL, NULL, 'usage', 'active', 'System'),
    ((SELECT id FROM product.m_products WHERE code = 'IOT_CORE'), (SELECT id FROM product.m_product_specifications WHERE code = 'IOT_CORE'), 'monthly', 'message', 0.0005, NULL, 100000.0, 'connection', 'active', 'System'),
    ((SELECT id FROM product.m_products WHERE code = 'DMS'), (SELECT id FROM product.m_product_specifications WHERE code = 'DMS-BASIC'), 'migration', 'GB transferred', 0.125, NULL, 2000.0, 'data-transfer', 'active', 'System');

INSERT INTO transaction.t_instances (code, name, account_id, product_id, product_spec_id, project_id, pricing_model_id, effectived_date, expired_date, row_status, created_by, created_date)
VALUES 
    ('INST_441682894486_1', 'Instance for ascend-group Product 1', (SELECT id FROM master.m_accounts WHERE code = '441682894486'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '441682894486') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_441682894486_2', 'Instance for ascend-group Product 2', (SELECT id FROM master.m_accounts WHERE code = '441682894486'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '441682894486') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_441682894486_3', 'Instance for ascend-group Product 3', (SELECT id FROM master.m_accounts WHERE code = '441682894486'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '441682894486') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_441682894486_4', 'Instance for ascend-group Product 4', (SELECT id FROM master.m_accounts WHERE code = '441682894486'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '441682894486') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_441682894486_5', 'Instance for ascend-group Product 5', (SELECT id FROM master.m_accounts WHERE code = '441682894486'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '441682894486') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp);

INSERT INTO transaction.t_instances (code, name, account_id, product_id, product_spec_id, project_id, pricing_model_id, effectived_date, expired_date, row_status, created_by, created_date)
VALUES 
    ('INST_429092326773_1', 'Instance for ascend-money Product 1', (SELECT id FROM master.m_accounts WHERE code = '429092326773'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '429092326773') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_429092326773_2', 'Instance for ascend-money Product 2', (SELECT id FROM master.m_accounts WHERE code = '429092326773'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '429092326773') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_429092326773_3', 'Instance for ascend-money Product 3', (SELECT id FROM master.m_accounts WHERE code = '429092326773'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '429092326773') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_429092326773_4', 'Instance for ascend-money Product 4', (SELECT id FROM master.m_accounts WHERE code = '429092326773'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '429092326773') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_429092326773_5', 'Instance for ascend-money Product 5', (SELECT id FROM master.m_accounts WHERE code = '429092326773'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '429092326773') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp);

INSERT INTO transaction.t_instances (code, name, account_id, product_id, product_spec_id, project_id, pricing_model_id, effectived_date, expired_date, row_status, created_by, created_date)
VALUES 
    ('INST_936922002519_1', 'Instance for ascend-commerce Product 1', (SELECT id FROM master.m_accounts WHERE code = '936922002519'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '936922002519') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_936922002519_2', 'Instance for ascend-commerce Product 2', (SELECT id FROM master.m_accounts WHERE code = '936922002519'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '936922002519') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_936922002519_3', 'Instance for ascend-commerce Product 3', (SELECT id FROM master.m_accounts WHERE code = '936922002519'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '936922002519') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_936922002519_4', 'Instance for ascend-commerce Product 4', (SELECT id FROM master.m_accounts WHERE code = '936922002519'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '936922002519') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_936922002519_5', 'Instance for ascend-commerce Product 5', (SELECT id FROM master.m_accounts WHERE code = '936922002519'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '936922002519') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp);

INSERT INTO transaction.t_instances (code, name, account_id, product_id, product_spec_id, project_id, pricing_model_id, effectived_date, expired_date, row_status, created_by, created_date)
VALUES 
    ('INST_116819170887_1', 'Instance for true-idc Product 1', (SELECT id FROM master.m_accounts WHERE code = '116819170887'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '116819170887') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_116819170887_2', 'Instance for true-idc Product 2', (SELECT id FROM master.m_accounts WHERE code = '116819170887'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '116819170887') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_116819170887_3', 'Instance for true-idc Product 3', (SELECT id FROM master.m_accounts WHERE code = '116819170887'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '116819170887') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_116819170887_4', 'Instance for true-idc Product 4', (SELECT id FROM master.m_accounts WHERE code = '116819170887'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '116819170887') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_116819170887_5', 'Instance for true-idc Product 5', (SELECT id FROM master.m_accounts WHERE code = '116819170887'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '116819170887') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp);

INSERT INTO transaction.t_instances (code, name, account_id, product_id, product_spec_id, project_id, pricing_model_id, effectived_date, expired_date, row_status, created_by, created_date)
VALUES 
    ('INST_655484151593_1', 'Instance for ascend-bit Product 1', (SELECT id FROM master.m_accounts WHERE code = '655484151593'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '116819170887') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_655484151593_2', 'Instance for ascend-bit Product 2', (SELECT id FROM master.m_accounts WHERE code = '655484151593'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '116819170887') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_655484151593_3', 'Instance for ascend-bit Product 3', (SELECT id FROM master.m_accounts WHERE code = '655484151593'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '116819170887') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_655484151593_4', 'Instance for ascend-bit Product 4', (SELECT id FROM master.m_accounts WHERE code = '655484151593'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '116819170887') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_655484151593_5', 'Instance for ascend-bit Product 5', (SELECT id FROM master.m_accounts WHERE code = '655484151593'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '116819170887') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp);

INSERT INTO transaction.t_instances (code, name, account_id, product_id, product_spec_id, project_id, pricing_model_id, effectived_date, expired_date, row_status, created_by, created_date)
VALUES 
    ('INST_772313499959_1', 'Instance for true-corporation Product 1', (SELECT id FROM master.m_accounts WHERE code = '772313499959'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '772313499959') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_772313499959_2', 'Instance for true-corporation Product 2', (SELECT id FROM master.m_accounts WHERE code = '772313499959'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '772313499959') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_772313499959_3', 'Instance for true-corporation Product 3', (SELECT id FROM master.m_accounts WHERE code = '772313499959'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '772313499959') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_772313499959_4', 'Instance for true-corporation Product 4', (SELECT id FROM master.m_accounts WHERE code = '772313499959'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '772313499959') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_772313499959_5', 'Instance for true-corporation Product 5', (SELECT id FROM master.m_accounts WHERE code = '772313499959'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '772313499959') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp);

INSERT INTO transaction.t_instances (code, name, account_id, product_id, product_spec_id, project_id, pricing_model_id, effectived_date, expired_date, row_status, created_by, created_date)
VALUES 
    ('INST_998795981022_1', 'Instance for truemove-h Product 1', (SELECT id FROM master.m_accounts WHERE code = '998795981022'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '998795981022') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_998795981022_2', 'Instance for truemove-h Product 2', (SELECT id FROM master.m_accounts WHERE code = '998795981022'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '998795981022') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_998795981022_3', 'Instance for truemove-h Product 3', (SELECT id FROM master.m_accounts WHERE code = '998795981022'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '998795981022') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_998795981022_4', 'Instance for truemove-h Product 4', (SELECT id FROM master.m_accounts WHERE code = '998795981022'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '998795981022') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_998795981022_5', 'Instance for truemove-h Product 5', (SELECT id FROM master.m_accounts WHERE code = '998795981022'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '998795981022') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp);

INSERT INTO transaction.t_instances (code, name, account_id, product_id, product_spec_id, project_id, pricing_model_id, effectived_date, expired_date, row_status, created_by, created_date)
VALUES 
    ('INST_684957738202_1', 'Instance for true-visions Product 1', (SELECT id FROM master.m_accounts WHERE code = '684957738202'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '684957738202') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_684957738202_2', 'Instance for true-visions Product 2', (SELECT id FROM master.m_accounts WHERE code = '684957738202'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '684957738202') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_684957738202_3', 'Instance for true-visions Product 3', (SELECT id FROM master.m_accounts WHERE code = '684957738202'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '684957738202') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_684957738202_4', 'Instance for true-visions Product 4', (SELECT id FROM master.m_accounts WHERE code = '684957738202'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '684957738202') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_684957738202_5', 'Instance for true-visions Product 5', (SELECT id FROM master.m_accounts WHERE code = '684957738202'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '684957738202') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp);

INSERT INTO transaction.t_instances (code, name, account_id, product_id, product_spec_id, project_id, pricing_model_id, effectived_date, expired_date, row_status, created_by, created_date)
VALUES 
    ('INST_682545126939_1', 'Instance for true-online Product 1', (SELECT id FROM master.m_accounts WHERE code = '682545126939'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '682545126939') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_682545126939_2', 'Instance for true-online Product 2', (SELECT id FROM master.m_accounts WHERE code = '682545126939'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '682545126939') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_682545126939_3', 'Instance for true-online Product 3', (SELECT id FROM master.m_accounts WHERE code = '682545126939'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '682545126939') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_682545126939_4', 'Instance for true-online Product 4', (SELECT id FROM master.m_accounts WHERE code = '682545126939'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '682545126939') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp),
    ('INST_682545126939_5', 'Instance for true-online Product 5', (SELECT id FROM master.m_accounts WHERE code = '682545126939'), (SELECT id FROM product.m_products ORDER BY RANDOM() LIMIT 1), (SELECT id FROM product.m_product_specifications ORDER BY RANDOM() LIMIT 1), (SELECT id FROM project.t_projects WHERE account_id = (SELECT id FROM master.m_accounts WHERE code = '682545126939') LIMIT 1), (SELECT id FROM product.m_pricing_model ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active', 'System', current_timestamp);

-- marketplace
INSERT INTO marketplace.m_vendors (code, name, row_status)
VALUES 
    ('TREND_MICRO', 'Trend Micro','active'),
    ('CROWDSTRIKE', 'CrowdStrike', 'active'),
    ('SPLUNK', 'Splunk', 'active'),
    ('SNOWFLAKE', 'Snowflake', 'active'),
    ('DATABRICKS', 'Databricks', 'active'),
    ('H2O', 'H2O.ai','active');

-- Insert mock data into marketplace.m_products for AWS Marketplace products
INSERT INTO marketplace.m_products (code, name, description, product_category_id, vendor_id, price_per_unit, unit, row_status)
VALUES
    ('TREND_MICRO_CLOUD_ONE', 'Trend Micro Cloud One', 'Security and compliance service.', (SELECT id FROM product.m_product_categories WHERE code = 'SECURITY'), (SELECT id FROM marketplace.m_vendors WHERE code = 'TREND_MICRO'), 0.05, 'GB', 'active'),
    ('CROWDSTRIKE_FALCON', 'CrowdStrike Falcon', 'Cloud-native endpoint protection.', (SELECT id FROM product.m_product_categories WHERE code = 'SECURITY'), (SELECT id FROM marketplace.m_vendors WHERE code = 'CROWDSTRIKE'), 0.1, 'Endpoint', 'active'),
    ('SPLUNK_CLOUD', 'Splunk Cloud', 'SIEM for security event monitoring.', (SELECT id FROM product.m_product_categories WHERE code = 'ANALYTICS'), (SELECT id FROM marketplace.m_vendors WHERE code = 'SPLUNK'), 0.2, 'GB', 'active'),
    ('SNOWFLAKE', 'Snowflake', 'Data warehousing solution.', (SELECT id FROM product.m_product_categories WHERE code = 'DATABASE'), (SELECT id FROM marketplace.m_vendors WHERE code = 'SNOWFLAKE'), 0.3, 'TB', 'active'),
    ('DATABRICKS', 'Databricks', 'Analytics and AI platform.', (SELECT id FROM product.m_product_categories WHERE code = 'ANALYTICS'), (SELECT id FROM marketplace.m_vendors WHERE code = 'DATABRICKS'), 0.4, 'TB', 'active'),
    ('H2O_AI', 'H2O.ai', 'AI and machine learning platform.', (SELECT id FROM product.m_product_categories WHERE code = 'ML_AI'), (SELECT id FROM marketplace.m_vendors WHERE code = 'H2O'), 0.15, 'Model', 'active');

INSERT INTO marketplace.t_instances (code, name, account_id, product_id, effective_date, expired_date, row_status)
VALUES 
    ('INST_AG_001', 'ascend-money-instance-1', (SELECT id FROM master.m_accounts WHERE code = '429092326773'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_AG_002', 'ascend-money-instance-2', (SELECT id FROM master.m_accounts WHERE code = '429092326773'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_AG_003', 'ascend-commerce-instance-1', (SELECT id FROM master.m_accounts WHERE code = '936922002519'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_AG_004', 'ascend-commerce-instance-2', (SELECT id FROM master.m_accounts WHERE code = '936922002519'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_AG_005', 'true-idc-instance-1', (SELECT id FROM master.m_accounts WHERE code = '116819170887'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_AG_006', 'true-idc-instance-2', (SELECT id FROM master.m_accounts WHERE code = '116819170887'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_AG_007', 'ascend-bit-instance-1', (SELECT id FROM master.m_accounts WHERE code = '655484151593'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_AG_008', 'ascend-bit-instance-2', (SELECT id FROM master.m_accounts WHERE code = '655484151593'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_AG_009', 'egg-digital-instance-1', (SELECT id FROM master.m_accounts WHERE code = '912577240677'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_AG_010', 'egg-digital-instance-2', (SELECT id FROM master.m_accounts WHERE code = '912577240677'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_TC_001', 'truemove-h-instance-1', (SELECT id FROM master.m_accounts WHERE code = '998795981022'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_TC_002', 'truemove-h-instance-2', (SELECT id FROM master.m_accounts WHERE code = '998795981022'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_TC_003', 'true-visions-instance-1', (SELECT id FROM master.m_accounts WHERE code = '684957738202'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_TC_004', 'true-visions-instance-2', (SELECT id FROM master.m_accounts WHERE code = '684957738202'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_TC_005', 'true-online-instance-1', (SELECT id FROM master.m_accounts WHERE code = '682545126939'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active'),
    ('INST_TC_006', 'true-online-instance-2', (SELECT id FROM master.m_accounts WHERE code = '682545126939'), (SELECT id FROM marketplace.m_products ORDER BY RANDOM() LIMIT 1), current_timestamp, NULL, 'active');